### ISSUE TITLE
GDPR infringement

### ISSUE THREAD

**Issue by rschrenk** [open-lms-open-source/moodle-mod_mediagallery#24]
Hello,

we recognized, that mod_mediagallery imports Google Fonts in https://github.com/open-lms-open-source/moodle-mod_mediagallery/blob/80ba8fa06350506b8dd5ee4284f63fdf04f93d3a/css/fontawesome.min.css#L5

As for European sites, this causes an infringement of the GDPR. Would it be possible to offer a localized version of the Google fonts integrated in your plugin?

Kind regards

**Comment by aolley** [comment]
This  is taken care of in cff1c901bd31f3135df309614806b234d91716ae
A new release will go out soon including that.

**Comment by rschrenk** [comment]
thank you very much for the fast fix of this issue!
